allowBuilds:
  '@tailwindcss/oxide': true
  better-sqlite3: true
  core-js: false
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@astrojs/internal-helpers@0.10.4'
  - '@astrojs/node@11.1.4'
