name: Deploy Astro SSR to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Deploy Astro SSR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      # Subimos el proyecto completo mediante FTPS
      - name: Upload project to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21

          # Carpeta donde está tu aplicación Node en cPanel
          server-dir: astro-travels/